import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { 
  Sparkles, 
  Cpu, 
  CheckCircle2, 
  AlertTriangle, 
  Clock, 
  Building2, 
  CloudRain, 
  Radio, 
  Sliders, 
  ArrowRight,
  ShieldCheck,
  AlertCircle
} from 'lucide-react';

export const SmartAutomationHub: React.FC = () => {
  const { recommendations, applyRecommendation, centers } = useApp();

  return (
    <div className="space-y-6 animate-fade-in pb-12">
      {/* Header */}
      <div>
        <div className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold mb-2">
          <Sparkles className="w-3.5 h-3.5 text-emerald-600" />
          <span>DoCA Intelligent Mandi Telemetry</span>
        </div>
        <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900">
          Smart Automation & AI Load Balancer
        </h2>
        <p className="text-xs text-slate-500">
          Intelligent rule engines and predictive algorithms that dynamically balance farmer arrival queues, prevent traffic bottlenecks, and optimize weighbridge operations.
        </p>
      </div>

      {/* Telemetry Operational Banner */}
      <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-3.5 flex items-center space-x-3 text-xs text-emerald-950">
        <ShieldCheck className="w-4 h-4 text-emerald-700 shrink-0" />
        <span>
          <strong>Automated Load Balancing:</strong> Predictive rules, weather alerts, and dynamic capacity-balancing logic are calibrated using real-time queue models.
        </span>
      </div>

      {/* 4 Core Smart Automation Pillars */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-2">
          <div className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-800 flex items-center justify-center font-bold">
            <Clock className="w-5 h-5" />
          </div>
          <h4 className="font-bold text-slate-900 text-sm">Dynamic Queue Estimator</h4>
          <p className="text-xs text-slate-500 leading-relaxed">
            Calculates wait time dynamically using <code className="bg-slate-100 px-1 py-0.5 rounded text-[11px]">T = (Q × P) / N</code> based on active weighbridges and real-time sampling.
          </p>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-2">
          <div className="w-10 h-10 rounded-xl bg-blue-100 text-blue-800 flex items-center justify-center font-bold">
            <Building2 className="w-5 h-5" />
          </div>
          <h4 className="font-bold text-slate-900 text-sm">Capacity Gatekeeper</h4>
          <p className="text-xs text-slate-500 leading-relaxed">
            Strict mathematical ceiling per 30-min window prevents overbooking and eliminates highway spillover queues.
          </p>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-2">
          <div className="w-10 h-10 rounded-xl bg-amber-100 text-amber-800 flex items-center justify-center font-bold">
            <Sliders className="w-5 h-5" />
          </div>
          <h4 className="font-bold text-slate-900 text-sm">Auto-Rerouting Engine</h4>
          <p className="text-xs text-slate-500 leading-relaxed">
            When a hub hits 85% load, nearby depots within 8km are automatically recommended to walk-in and online farmers.
          </p>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-2">
          <div className="w-10 h-10 rounded-xl bg-purple-100 text-purple-800 flex items-center justify-center font-bold">
            <Radio className="w-5 h-5" />
          </div>
          <h4 className="font-bold text-slate-900 text-sm">Proactive SMS Alerts</h4>
          <p className="text-xs text-slate-500 leading-relaxed">
            Automated SMS triggers when farmer is 5 positions away, ensuring zero idle waiting and timely tractor movement.
          </p>
        </div>
      </div>

      {/* Live AI Recommendations Feed */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-5">
        <div className="flex items-center justify-between pb-3 border-b border-slate-200">
          <div>
            <h3 className="font-bold text-slate-900 text-sm flex items-center space-x-2">
              <Cpu className="w-4 h-4 text-emerald-700" />
              <span>Real-Time Operational Automation Recommendations</span>
            </h3>
            <p className="text-xs text-slate-500">Live actionable insights generated by the smart dispatch engine.</p>
          </div>
          <span className="text-xs font-bold text-amber-800 bg-amber-50 px-3 py-1 rounded-full border border-amber-200">
            {recommendations.filter(r => r.status === 'active').length} Action Items Pending
          </span>
        </div>

        <div className="space-y-4">
          {recommendations.map((rec) => {
            const isApplied = rec.status === 'applied';

            return (
              <div
                key={rec.id}
                className={`p-5 rounded-2xl border transition-all ${
                  isApplied
                    ? 'bg-slate-50 border-slate-200 opacity-75'
                    : rec.type === 'congestion'
                    ? 'bg-amber-50/50 border-amber-300'
                    : rec.type === 'reroute'
                    ? 'bg-blue-50/50 border-blue-300'
                    : 'bg-purple-50/50 border-purple-300'
                }`}
              >
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 mb-2">
                  <div className="flex items-center space-x-2">
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase ${
                      isApplied ? 'bg-slate-200 text-slate-700' : 'bg-amber-500 text-slate-950'
                    }`}>
                      {rec.type.toUpperCase()}
                    </span>
                    <h4 className="font-bold text-sm text-slate-900">{rec.title}</h4>
                  </div>
                  <span className="text-[11px] text-slate-400 font-mono">{rec.timestamp}</span>
                </div>

                <p className="text-xs text-slate-700 mb-2 leading-relaxed">{rec.description}</p>

                <div className="bg-white/80 p-3 rounded-xl border border-slate-200 text-xs space-y-1 mb-3">
                  <div className="text-slate-900"><strong>Suggested Automated Action:</strong> {rec.suggestedAction}</div>
                  <div className="text-emerald-700 font-semibold flex items-center space-x-1">
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Projected Impact: {rec.impactMetric}</span>
                  </div>
                </div>

                <div className="flex items-center justify-between pt-1">
                  <span className="text-xs text-slate-500">Center: <strong>{rec.centerName}</strong></span>
                  {isApplied ? (
                    <span className="text-xs font-bold text-emerald-700 flex items-center space-x-1">
                      <CheckCircle2 className="w-4 h-4" />
                      <span>Automation Executed</span>
                    </span>
                  ) : (
                    <button
                      onClick={() => applyRecommendation(rec.id)}
                      className="px-4 py-2 bg-emerald-700 hover:bg-emerald-800 text-white rounded-xl text-xs font-bold transition shadow-sm flex items-center space-x-1"
                    >
                      <span>Apply Recommendation</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
